// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250815151922_AdicionadoNameMethod")]
    partial class AdicionadoNameMethod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bradley Corwin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Suzanne Schowalter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sherman Kreiger"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Terrence Lemke"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rudolph Schumm"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Desiree Nicolas"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sandy Greenfelder"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Terrell Moore"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Russell Schuppe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gordon Ullrich"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cary Weimann"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grady Heidenreich"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ella Fay"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Antonia Langosh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kelli Stokes"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Angelica Shanahan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Marcella Walker"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Elaine Mitchell"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ramona Jacobi"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Doris Bradtke"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("MethodPayment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Awesome Metal Gloves"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Generic Granite Car"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sleek Cotton Fish"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ergonomic Plastic Sausages"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ergonomic Plastic Car"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fantastic Soft Computer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tasty Rubber Table"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Practical Cotton Table"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rustic Frozen Bike"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gorgeous Granite Gloves"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Licensed Frozen Sausages"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Generic Fresh Gloves"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Incredible Granite Pizza"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Generic Rubber Pants"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Unbranded Steel Pizza"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sleek Granite Gloves"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Practical Metal Chair"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Licensed Fresh Chips"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
